# https://docs.rubocop.org/rubocop/1.24/cops_style.html

AllCops:
  NewCops: enable

Style/BlockDelimiters:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/GuardClause:
  Enabled: false

Metrics/MethodLength:
  Max: 20
Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
Metrics/AbcSize:
  CountRepeatedAttributes: false
  Max: 30
Metrics/PerceivedComplexity:
  Max: 10
Metrics/CyclomaticComplexity:
  Max: 10

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
